name: cd

on:
  push:
    branches:
      - main

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - name: Deploy Using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 2233
          script: |
          
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh    

            PATH="/usr/local/go/bin/:$PATH"
          
            cd /github/CanopyCore
            git pull origin main
            git status
            
            docker-compose down
            docker-compose build
            docker-compose up